### PR TITLE
fix(SFT-2498): notifications not sending when `Store Submitted Data for this Form` is disabled

### LINKED ISSUE #2252: Call to a member function getFormFieldValues() on null in AiBundle.php during form submission
### What happened?

Issue Summary

After upgrading to Freeform 5.13.3, all form submissions fail with a fatal error in AiBundle.php:78. The error occurs when the spam validation job runs asynchronously and the AI Bundle attempts to access form field values on a null form object.

If I enable "Bypass All Spam Checks for Logged in Users" it submits ok for a logged in user.

Environment

- Freeform version: 5.13.3
- Craft CMS version: 4.16.15
- PHP version: 8.0.2
- Integrations enabled: None
- AI integrations configured: None

Form submission fails with the following error:

Exception 'Error' with message 'Call to a member function getFormFieldValues() on null' in /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Integrations/AI/AiBundle.php:78

### Errors and Stack Trace (if available)

```shell
Exception 'Error' with message 'Call to a member function getFormFieldValues() on null' in /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Integrations/AI/AiBundle.php:78

Stack trace:
#0 [internal function]: Solspace\Freeform\Integrations\AI\AiBundle->addAiValuesToJobPostedData(Object(Solspace\Freeform\Events\Integrations\ProcessPostedValuesEvent))
#1 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(Solspace\Freeform\Events\Integrations\ProcessPostedValuesEvent))
#2 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Jobs/ProcessSpamValidationJob.php(35): yii\base\Event::trigger('Solspace\\Freefo...', 'process-posted-...', Object(Solspace\Freeform\Events\Integrations\ProcessPostedValuesEvent))
#3 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Jobs/FreeformQueueHandler.php(48): Solspace\Freeform\Jobs\ProcessSpamValidationJob->execute(Object(craft\queue\Queue))
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Integrations/SpamBlocking/SpamBlockingBundle.php(109): Solspace\Freeform\Jobs\FreeformQueueHandler->queueJob(Object(Solspace\Freeform\Jobs\ProcessSpamValidationJob), 200, false)
#5 [internal function]: Solspace\Freeform\Integrations\SpamBlocking\SpamBlockingBundle->validateAsync(Object(Solspace\Freeform\Events\Forms\SubmitEvent))
#6 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(Solspace\Freeform\Events\Forms\SubmitEvent))
#7 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Services/SubmissionsService.php(219): yii\base\Event::trigger('Solspace\\Freefo...', 'after-submit', Object(Solspace\Freeform\Events\Forms\SubmitEvent))
#8 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/SubmitController.php(47): Solspace\Freeform\Services\SubmissionsService->handleSubmission(Object(Solspace\Freeform\Form\Types\Regular))
#9 [internal function]: Solspace\Freeform\controllers\SubmitController->actionIndex()
#10 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('freeform/submit', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(648): craft\web\Application->runAction('freeform/submit', Array)
#15 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /var/www/html/web/index.php(12): yii\base\Application->run()
#18 {main}
```

### How can we reproduce this?

1. Upgrade from Freeform 4.1.28 to 5.13.3
2. Submit any form (with no AI integrations configured)
3. Error occurs during async spam validation

### Freeform Edition

Pro

### Freeform Version

5.13.3

### Craft Version

4.16.15

### When did this issue start?

- [ ] Unsure
- [ ] Fresh install of Freeform
- [x] After upgrading from older Freeform version
- [ ] After upgrading from older Craft version
- [ ] After a change to hosting configuration

### Previous Freeform Version

4.1.28

### PR DESCRIPTION
**Pull request by seandelaney**
Fixes: https://github.com/solspace/craft-freeform/issues/2252

### CODE REVIEW

File: packages/plugin/src/Jobs/SendNotificationsJob.php [hunk 1]
```diff
@@ -88,8 +90,17 @@ public function execute($queue): void
...
-        if (!$submission || $submission->isSpam) {
+        $submission = null;
+        if ($this->submissionId) {
+            $submission = $freeform->submissions->getSubmissionById($this->submissionId);
+        }
+
+        // If no stored submission and we have posted data, fabricate one in-memory
+        if (!$submission && $this->postedData) {
+            $submission = $this->createTmpSubmission($form);
+        }
```
Comment (gustavs-gutmanis) [inline packages/plugin/src/Jobs/SendNotificationsJob.php]: Even if posted data could be empty, it should still be present every time, so we can always create a new submission in the case of missing submission ID

```suggestion
        $submission = null;
        if ($this->submissionId) {
            $submission = $freeform->submissions->getSubmissionById($this->submissionId);
        } else {
            // If no stored submission - fabricate one in-memory
            $submission = $this->createTmpSubmission($form);
        }
```

File: packages/plugin/src/Jobs/SendNotificationsJob.php [hunk 2]
```diff
@@ -123,4 +134,35 @@ private function getLogger(?NotificationInterface $notification, Form $form): Lo
...
+        $tmpTitle = \Craft::$app->view->renderString(
+            $form->getSettings()->getGeneral()->submissionTitle,
+            array_merge(
+                [],
+                [
+                    'dateCreated' => $dateCreated,
+                    'form' => $form,
+                ]
+            )
+        );
```
Comment (gustavs-gutmanis) [inline packages/plugin/src/Jobs/SendNotificationsJob.php]: There's a `Submission::generateTitle()` method for generating titles. See if we can reuse it here. It needs a submission instance and a form.

**Review by gustavs-gutmanis — COMMENTED** [review]
Nice

**Review by kjmartens — APPROVED** [review]
